# Generated by Django 4.1.7 on 2023-03-21 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesseArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayOfWeek', models.IntegerField(default=-1)),
                ('Zeit', models.TimeField(default=datetime.datetime.now)),
                ('MinisInsgesamt', models.IntegerField(default=2)),
                ('OberminisAnzahl', models.IntegerField(default=2)),
                ('Name', models.TextField()),
                ('Print', models.TextField(default='$date - $day $time $info')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatID', models.IntegerField(default=-1)),
                ('abo', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('secretKey', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('PlanArt', models.IntegerField(choices=[(0, 'dragdrop'), (1, 'toggle')])),
                ('StartDatum', models.DateField(default=datetime.datetime.now)),
                ('EndDatum', models.DateField(default=datetime.datetime.now)),
                ('Archiviert', models.BooleanField(default=False)),
                ('AbfrageEnde', models.DateField(blank=True, default=None, null=True)),
                ('DefaultMesseArt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.messeart')),
            ],
        ),
        migrations.CreateModel(
            name='Mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adresse', models.TextField(default='')),
                ('Geburtsdatum', models.DateField(default=django.utils.timezone.now)),
                ('MiniTyp', models.IntegerField(choices=[(0, 'Obermini'), (1, 'Mini'), (2, 'Minimini'), (3, 'Passiv'), (4, 'Verwalter'), (5, 'Ausgetreten'), (6, 'Sysadmin')], default=0)),
                ('Geschwister', models.IntegerField(default=-1)),
                ('Telefon', models.CharField(default='0', max_length=20)),
                ('AnzahlEingeteilt', models.IntegerField(default=0)),
                ('StartEingeteilt', models.IntegerField(default=0)),
                ('PateMini', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mini')),
                ('telegram', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini', to='api.telegramchat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField(default=datetime.datetime.now)),
                ('Info', models.TextField(blank=True, default='')),
                ('explizit', models.BooleanField(default=False)),
                ('autogenerated', models.BooleanField(default=False)),
                ('Zeit', models.TimeField(default=datetime.datetime.now)),
                ('notify', models.IntegerField(default=0)),
                ('Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.messeart')),
                ('Plan_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Messen', to='api.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eingeteilt', models.BooleanField(default=False)),
                ('Messe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gruppen', to='api.messe')),
                ('Minis', models.ManyToManyField(related_name='Gruppen', to='api.mini')),
            ],
        ),
        migrations.CreateModel(
            name='Abfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=100)),
                ('Nachricht', models.TextField(default='')),
                ('edit', models.BooleanField(default=False)),
                ('Mini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Abfrage', to='api.mini')),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
    ]
