# Generated by Django 4.1.7 on 2024-04-02 09:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_mini_anzahleingeteilt_mini_offseteinteilung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="LinkKey",
            field=models.CharField(
                default=api.models.__generateRandomString__, max_length=200
            ),
        ),
    ]
