/*import { FormBuilder } from "@angular/forms";
import { DBServiceTest } from "../service/db.service.spec";
import { IGottesdienst, GottesdiensteService, IGottesdienst_Art } from "../service/gottesdienste.service";
import { GottesdiensteComponent } from "./art-verwaltung.component";

describe("Teste Gottesdienste", () => {

    let component: GottesdiensteComponent;
    let db: DBServiceTest;
    let gds: IGottesdienst[];
    let artList: IGottesdienst_Art[];
    let gdService: GottesdiensteService;*/

    /*beforeAll(() => {
        db = new DBServiceTest();
        gds = [{id: 100, Art: 0, Datum: new Date(), Info: "Test", Plan_id: null, explizit: false, autogenerated: false}]; artList = [];
        //Gottesdienst laden
        let b1 = false, b2 = false;
        db.addGetFunction('gottesdienste/messe/all/', () => {
            b1 = true;
            return {data: gds};
        });
        db.addGetFunction('gottesdienste/art/all/', () => {
            b2 = true;
            return {data: artList};
        });
        gdService = new GottesdiensteService(db);
        component = new GottesdiensteComponent(new FormBuilder(), db, gdService);
        expect(b1).toBeTruthy(); expect(b2).toBeTruthy();
        component.ngOnInit();
        expect(component.gd_form).not.toBeNull();
    });

    it("Neuer Gottesdienste", () => {
            const gd = {Art: 0, Datum: new Date(2020, 2, 20), Info: "Hello World", Plan_id: null, explizit: false, id: -1};
            component.gd_form.setValue(gd);
            let executed = false;
            db.addPostFunc('gottesdienste/messe/neu/', (url, data: any) => {
                expect(data).toEqual(gd);
                executed = true;
                return data.id;
            });
            component.gd_speichern();
            expect(executed).toBeTruthy();
            gd.Art = -13;
            componentgottesdienste.gd_form.setValue(gd);
            executed = false;
            component.gd_speichern();
            expect(executed).toBeFalsy();
            gd.Art = 10;
            gd.id = -123;
            component.gd_form.setValue(gd);
            component.gd_speichern();
            expect(executed).toBeFalsy();
    });*/

    /*it("Gottesdienst_selection", () => {
        gdService.gd_List = {
            1: {Art: 0, Datum: new Date(2020, 12, 3), Info: "Hello World", Plan_id: null, explizit: false, id: 1, autogenerated: false},
            2: {Art: 0, Datum: new Date(2000, 6, 3), Info: null, Plan_id: 14, explizit: true, id: 2, autogenerated: false}
        }
        component.gd_selectedChanged(1);
        //expect(gdService.gd_List[1]).toEqual(component.gd_form.value);
        component.gd_selectedChanged(2);
        //expect(gdService.gd_List[2]).toEqual(component.gd_form.value);
        component.gd_selectedChanged(-1);
        //expect(component.gd_form.value).toBeDefined();
    });*/

//});

/*describe("Teste Gottesdienstart", () => {
    let component: GottesdiensteComponent;
    let db: DBServiceTest;
    let artList: IGottesdienst_Art[];
    let gdService: GottesdiensteService;

    beforeAll(() => {
        db = new DBServiceTest();
        //Gottesdienst laden
        artList = [{id: 2, DayOfWeek: 6, MinisInsgesamt: 10, Name: "Test Art", OberminisAnzahl: 3, Print: "hahaha", Zeit: "12:03:00"},
                    {id: 3, DayOfWeek: 5, MinisInsgesamt: 11, Name: "Test Art2", OberminisAnzahl: 1, Print: "haha", Zeit: "00:03:00"}];
        //
        let b1 = false, b2 = false;
        db.addGetFunction('gottesdienste/messe/all/', () => {
            b1 = true;
            return {data: []};
        });
        db.addGetFunction('gottesdienste/art/all/', () => {
            b2 = true;
            return {data: artList};
        });
        gdService = new GottesdiensteService(db);
        component = new GottesdiensteComponent(new FormBuilder(), db, gdService);
        expect(b1).toBeTruthy(); expect(b2).toBeTruthy();
        component.ngOnInit();
        expect(component.art_form).not.toBeNull();
    });*/

    /*it("Neue Art hinzufügen", () => {
        //Standart Neu
        const art: IGottesdienst_Art = {id: -1, DayOfWeek: 2, MinisInsgesamt: 14, Name: "TestGD", OberminisAnzahl: 3, Print: "- $day $time", Zeit: "00:12"};
        component.art_form.setValue(art);
        let neuCheck = false;
        db.addPostFunc("gottesdienste/art/neu/", (url, data) => {
            neuCheck = true;
            return 1;
        });
        db.justAllow = "gottesdienste/art/neu/";
        component.gd_Art_speichern();
        expect(neuCheck).toBeTruthy();
        // Falsche Eingabedaten
        art.MinisInsgesamt = 2;
        art.OberminisAnzahl = 10;
        component.art_form.setValue(art);
        neuCheck = false;
        component.gd_Art_speichern();
        expect(neuCheck).toBeFalsy();
    });

    it("ChangeArtSelection", () => {
        const def = {MinisInsgesamt: 0, Name: "", OberminisAnzahl: 0, Print: "$date - $day $time", Zeit: "--:--", id: -1, DayOfWeek: -1};
        component.artSelectionChanged(-1);
        expect(component.art_form.value).toEqual(def);
        component.artSelectionChanged(artList[1].id);
        expect(component.art_form.value).toEqual(artList[1]);
    });

    it("Art update", () => {
        component.artSelectionChanged(artList[0].id);
        expect(component.art_form.value).toEqual(artList[0]);
        // Änderung
        let deepcopy: IGottesdienst_Art = JSON.parse(JSON.stringify(artList[0]));
        deepcopy.MinisInsgesamt = 100;
        component.art_form.setValue(deepcopy);
        let checkUpdate = false;
        const uri = 'gottesdienste/art/update/' + artList[0].id.toString() + '/';
        db.addPostFunc(uri, (url, data) => {
            checkUpdate = true;
            expect(data).toEqual(deepcopy);
        });
        db.justAllow = uri;
        component.gd_Art_speichern();
    });
});*/
